apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: CICD
    role: admin
    version: v1
spec: 
  container: 
  - name: jenkins-cnt
    image: jenkins
    ports:
    - containerPort: 8080
      protocol: TCP

