apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jenkins
        version: 1.642.4
    spec:
      containers:
      - name: jenkins-pod
        image: jenkins:1.642.4
        ports:
        - containerPort: 8080
          protocol: TCP




