apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-rc
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    specs:
      containers:
      - name: hello-pod
        image: nginx
        ports:
        - containerPort: 80


