apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 10
  minReadySeconds: 10
  selector:
    matchLabels:
      role: vote
    matchExpressions:
      - {key: verson, operator: In, values: [v1,v2,v3]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v1
    spec:
      containers:
      - name: app
        image: schoolofdevops/vote:v1
        ports:
        - containerPort: 80
          protocol: TCP