
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote
spec:
  selector:
    role: vote
    version: v1
  type: NodePort
  port:
  - port: 80
    nodePort: 30000
    targetPort: 80

